package com.debugdesk.mono.utils

import com.debugdesk.mono.R

object Icons {
    val categoryIcons =
        listOf(
            R.drawable.baby to R.string.baby,
            R.drawable.bag to R.string.bag,
            R.drawable.bank to R.string.bank,
            R.drawable.bird to R.string.bird,
            R.drawable.birthday to R.string.birthday,
            R.drawable.boat to R.string.boat,
            R.drawable.books to R.string.books,
            R.drawable.brain to R.string.brain,
            R.drawable.building to R.string.building,
            R.drawable.camera to R.string.camera,
            R.drawable.car to R.string.car,
            R.drawable.cat to R.string.cat,
            R.drawable.chair to R.string.chair,
            R.drawable.challenge to R.string.challenge,
            R.drawable.clothes to R.string.clothes,
            R.drawable.coffee to R.string.coffee,
            R.drawable.coin_1 to R.string.coin_1,
            R.drawable.coin to R.string.coin,
            R.drawable.cook to R.string.cook,
            R.drawable.cup to R.string.cup,
            R.drawable.cycles to R.string.cycles,
            R.drawable.dinner to R.string.dinner,
            R.drawable.dog to R.string.dog,
            R.drawable.facemask to R.string.face_mask,
            R.drawable.fix to R.string.fix,
            R.drawable.flower to R.string.flower,
            R.drawable.food to R.string.food,
            R.drawable.football to R.string.football,
            R.drawable.`fun` to R.string.fun_,
            R.drawable.gas to R.string.gas,
            R.drawable.gift to R.string.gift,
            R.drawable.glass to R.string.glass,
            R.drawable.gym to R.string.gym,
            R.drawable.house to R.string.house,
            R.drawable.lawer to R.string.lawyer,
            R.drawable.map to R.string.map,
            R.drawable.market to R.string.market,
            R.drawable.medican to R.string.medicine,
            R.drawable.money to R.string.money,
            R.drawable.music to R.string.music,
            R.drawable.ic_package to R.string._package,
            R.drawable.party to R.string.party,
            R.drawable.pie to R.string.pie,
            R.drawable.pill to R.string.pill,
            R.drawable.plane to R.string.plane,
            R.drawable.receipt to R.string.receipt,
            R.drawable.run to R.string.run,
            R.drawable.sea to R.string.sea,
            R.drawable.shower to R.string.shower,
            R.drawable.store to R.string.store,
            R.drawable.study_1 to R.string.study_1,
            R.drawable.study to R.string.study,
            R.drawable.tennisball to R.string.tennis_ball,
            R.drawable.train to R.string.train,
            R.drawable.user to R.string.user,
            R.drawable.wallet to R.string.wallet,
            R.drawable.wc to R.string.wc,
        )
}
